version: "3"

services:
  backend:
    container_name: uploader_backend
    restart: always
    build: .
    command: sh -c "alembic upgrade head && python main.py"
    ports:
      - "8000:8000"
    env_file:
      - .env

  frontend:
    container_name: uploader_frontend
    restart: always
    build: .
    working_dir: /app/web/frontend
    command: sh -c "npm start"
    ports:
      - "3000:3000"
    env_file:
      - .env
